title: E. Adrian Henle
email: adrian@henletech.net
description: Machine Learning Engineering for Agentic AI Platforms and Internet Intelligence
linkedin_username: adrian-henle
github_username: eahenle

theme: minima
show_excerpts: true

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - USER_CUSTOM_INSTRUCTIONS.md
  - cacert.pem
  - serve.sh
