title: E. Adrian Henle
email: henlee@oregonstate.edu
description: Chemical Data Science
linkedin_username: adrian-henle

theme: minima
show_excerpts: true

minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/eahenle" }
    - { platform: twitter, user_url: "https://twitter.com/eahenle" }

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - old
  - README.md
  - cacert.pem
  - serve.sh
