title: E. Adrian Henle
email: henlee@oregonstate.edu
description: Data Science for Chemistry and Materials Research and Development
linkedin_username: adrian-henle
github_username: eahenle

theme: minima
show_excerpts: false
minima:
  skin: dark

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - cacert.pem
  - serve.sh
